# Generated by Django 2.1.1 on 2018-09-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180927_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueon_date',
            field=models.DateTimeField(verbose_name='date deadline'),
        ),
    ]
