# Generated by Django 2.1.1 on 2018-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180927_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dueon_date',
            field=models.DateField(verbose_name='date deadline'),
        ),
    ]
