# Generated by Django 2.1.1 on 2018-09-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('dueon_date', models.DateTimeField(verbose_name='date deadline')),
                ('status', models.CharField(choices=[('T', 'Task is completed'), ('F', 'Task is not completed')], default='F', max_length=1)),
                ('owner', models.CharField(max_length=10)),
            ],
        ),
    ]
